#!/bin/bash
#
#
#Name
#	isilonReport
#Description
#	This script is reading the report from Isilons and stores them for Tableau
#	This script is designed for cygwin as it is using UNC name path
#Options
#	-
#Author
#	Geri
#Versions
#	0.1 Initial version

#

#We are going to use hashes for the isilons, because we have to use IP addresses, because there is an issue with the DNS entries for the isilons...
#You can add more isilons, if you need to. Follow the syntax strictly
declare -A Isilons
Isilons[dc01isilon]=172.25.36.25
Isilons[dc02isilon]=172.27.204.24 

reportPath="\\\\ServerName\\Path\\"
isCygwin=`set | grep OSTYPE`

if [ isCygwin != "OSTYPE=cygwin" ]; then
	echo "This script was designed to use Cygwin terminal, because using UNC path names."
	echo "This is not a Cygwin terminal!"
	echo "Exiting..."
	exit
fi

#date format is: yyyy-mm-dd. It is easier to sort with this format
myDate=`date +%F`

#Now the report. I use root, but for that to work, you have to create your own RSA key pair
#Add it to the necessary file, and then you can run this script
#Otherwise it will give you an error message
for isilon in "${!Isilons[@]}"
do
	echo "Working on ${Isilons[$isilon]} $isilon"
	ssh -l root ${Isilons[$isilon]} -i ~/.ssh/id_rsa "isi quota quotas list --format=csv" > ${reportPath}${isilon}_${myDate}.csv
done

echo "My job is done..."
